environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'
    - nodejs_version: '8'
    - nodejs_version: '9'
    - nodejs_version: '10'

cache:
  - "%LOCALAPPDATA%/.npm"
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm test
  - npm run build

build: off
